name: rpmtw_account_ui
description: RPMTW Account

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  rpmtw_api_client_flutter: ^1.0.7+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  no_context_navigation: ^2.1.2
  flutter_login: ^3.2.0
  font_awesome_flutter: ^9.2.0
  file_picker: ^4.5.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/NotoSansCJKtc-Regular.otf #Source: https://fonts.google.com/noto
